// <auto-generated />
namespace KarmicEnergy.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dev4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dev4));
        
        string IMigrationMetadata.Id
        {
            get { return "201607071511565_Dev4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
